#
# Dockerfile for cpuminer
# usage: docker run creack/cpuminer --url xxxx --user xxxx --pass xxxx
# ex: docker run creack/cpuminer --url stratum+tcp://ltc.pool.com:80 --user creack.worker1 --pass abcdef
#
#

FROM		ubuntu:16.04
MAINTAINER	Jon Froiland <jon.froiland@gmail.com>

RUN		apt update -qq
RUN             apt udgrade -qqy
RUN		apt install -qqy automake
RUN		apt install -qqy libcurl4-openssl-dev
RUN		apt install -qqy git
RUN		apt install -qqy make
RUN		apt update -qq

RUN		git clone https://github.com/pooler/cpuminer

RUN		cd cpuminer && ./autogen.sh
RUN		cd cpuminer && ./configure CFLAGS="-O3"
RUN		cd cpuminer && make

WORKDIR		/cpuminer
ENTRYPOINT	["./cpuminer"]
